# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Compile README.md

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: Ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
        - name: latest
          cntr: dslabscl/dslab-covid-report:latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ matrix.cntr }}

      - name: Compilar
        run:  |
          docker run -v$(pwd):/home/report -w/home/report ${{ matrix.cntr }} \
            Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git add README_files/figure-gfm/* 
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Re-build Rmarkdown files' || echo Nothing has changed
          git push origin || echo "No changes to commit" 

